name: ci

on:
  push:
    branches: [ "master", "main" ]

permissions:
  security-events: write

jobs:
  # TRABAJO 1: BANDIT (Formato SARIF)
  bandit_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit and SARIF formatter
        # Bandit necesita un plugin extra para poder escribir en formato SARIF
        run: |
          pip install bandit
          pip install bandit-sarif-formatter

      - name: Run Bandit Scan
        # Cambiamos json por sarif
        run: bandit -r . -f sarif -o sast-bandit.sarif -ll -ii || true

      - name: Upload Bandit SARIF to Security Tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: sast-bandit.sarif
          category: bandit

  # TRABAJO 2: SEMGREP (Formato SARIF)
  semgrep_scan:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        # Semgrep ya soporta SARIF de forma nativa cambiando el flag
        run: semgrep scan --severity=ERROR --severity WARNING --sarif --output=sast-semgrep.sarif || true

      - name: Upload Semgrep SARIF to Security Tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: sast-semgrep.sarif
          category: semgrep
          
  # TRABAJO 3: DOCKER SCOUT (Construye la imagen y la escanea)
  docker_scout_scan:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest
    needs: [bandit_scan, semgrep_scan] # Espera a que terminen los análisis estáticos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PWD }}

      - name: Build Docker image
        run: docker build -t pygoat:latest .

      - name: Run Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: pygoat:latest
          only-severities: critical,high
          sarif-file: scout-report.sarif

      - name: Upload Docker Scout SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: scout-report.sarif
          category: docker-scout